"""Auto-generate a structured Markdown postmortem from an incident's timeline and tasks."""
from datetime import datetime, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.models.incident import Incident, IncidentParticipant
from app.models.task import Task
from app.models.timeline import TimelineEvent
from app.models.postmortem import Postmortem
from app.models.user import User


def _duration_str(start: datetime, end: datetime | None) -> str:
    if not end:
        return "Ongoing"
    delta = end - start
    total_minutes = int(delta.total_seconds() / 60)
    hours, minutes = divmod(total_minutes, 60)
    if hours and minutes:
        return f"{hours}h {minutes}m"
    if hours:
        return f"{hours}h"
    return f"{minutes}m"


def generate_markdown(incident: Incident, tasks: list[Task], author_name: str | None) -> str:
    now = datetime.now(timezone.utc)
    duration = _duration_str(incident.created_at, incident.resolved_at)
    fmt = "%Y-%m-%d %H:%M UTC"

    # Participants
    participant_lines = []
    for p in incident.participants:
        name = p.user.name if p.user else p.user_id
        participant_lines.append(f"- **{name}** ({p.role})")

    # Timeline table
    timeline_rows = []
    for event in incident.timeline:
        uname = event.user.name if event.user else "System"
        ts = event.created_at.strftime("%H:%M")
        desc = event.description.replace("|", "\\|")
        timeline_rows.append(f"| {ts} | {desc} | {uname} |")

    # Tasks
    done_tasks = [t for t in tasks if t.status == "done"]
    open_tasks = [t for t in tasks if t.status != "done"]

    task_lines = []
    for t in done_tasks:
        task_lines.append(f"- [x] {t.title}")
    for t in open_tasks:
        task_lines.append(f"- [ ] {t.title}")

    tags_str = ", ".join(f"`{t}`" for t in (incident.tags or []))
    topic_str = f"`{incident.topic}`" if incident.topic else "—"

    lines = [
        f"# Postmortem: {incident.title}",
        "",
        f"> **Auto-generated** by Project Overwatch on {now.strftime(fmt)}",
        "",
        "---",
        "",
        "## Overview",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Date** | {incident.created_at.strftime('%Y-%m-%d')} |",
        f"| **Severity** | {incident.severity.value.upper()} |",
        f"| **Status** | {incident.status.value.replace('_', ' ').title()} |",
        f"| **Duration** | {duration} |",
        f"| **Topic** | {topic_str} |",
        f"| **Tags** | {tags_str or '—'} |",
        f"| **Detected** | {incident.created_at.strftime(fmt)} |",
        f"| **Resolved** | {incident.resolved_at.strftime(fmt) if incident.resolved_at else 'Not yet'} |",
        "",
        "---",
        "",
        "## Summary",
        "",
        incident.description or "_No description provided. Fill in a brief summary of what happened._",
        "",
        "---",
        "",
        "## Timeline",
        "",
        f"_All times on {incident.created_at.strftime('%Y-%m-%d')}_",
        "",
        "| Time | Event | Who |",
        "|---|---|---|",
        *timeline_rows,
        "",
        "---",
        "",
        "## Participants",
        "",
        *participant_lines if participant_lines else ["_No participants recorded._"],
        "",
        "---",
        "",
    ]

    if task_lines:
        lines += [
            "## Tasks",
            "",
            *task_lines,
            "",
            "---",
            "",
        ]

    lines += [
        "## Root Cause Analysis",
        "",
        "_To be completed by the incident commander._",
        "",
        "**What broke:**",
        "",
        "> ",
        "",
        "**Why it broke:**",
        "",
        "> ",
        "",
        "**Why it wasn't caught earlier:**",
        "",
        "> ",
        "",
        "---",
        "",
        "## Impact",
        "",
        "_Describe the customer / business impact._",
        "",
        "> ",
        "",
        "---",
        "",
        "## Action Items",
        "",
        "| Action | Owner | Due |",
        "|---|---|---|",
        "| | | |",
        "",
        "---",
        "",
        "## Prevention",
        "",
        "_What changes will prevent this class of incident from recurring?_",
        "",
        "> ",
        "",
        "---",
        "",
        f"_Generated by Project Overwatch · {now.strftime(fmt)}_",
    ]

    return "\n".join(lines)


async def get_or_generate(
    db: AsyncSession,
    incident: Incident,
    actor: User,
    force_regenerate: bool = False,
) -> Postmortem:
    # Check for existing
    result = await db.execute(
        select(Postmortem).where(Postmortem.incident_id == incident.id)
    )
    existing = result.scalar_one_or_none()
    if existing and not force_regenerate:
        return existing

    # Load tasks
    tasks_result = await db.execute(
        select(Task).where(Task.incident_id == incident.id).order_by(Task.created_at)
    )
    tasks = list(tasks_result.scalars().all())

    # Re-load incident with full relations for generation
    full_result = await db.execute(
        select(Incident)
        .options(
            selectinload(Incident.participants).selectinload(IncidentParticipant.user),
            selectinload(Incident.timeline).selectinload(TimelineEvent.user),
        )
        .where(Incident.id == incident.id)
    )
    full_incident = full_result.scalar_one()

    content = generate_markdown(full_incident, tasks, actor.name)

    if existing:
        existing.content = content
        existing.updated_at = datetime.now(timezone.utc)
        await db.commit()
        await db.refresh(existing)
        return existing

    pm = Postmortem(incident_id=incident.id, content=content, created_by=actor.id)
    db.add(pm)
    await db.commit()
    await db.refresh(pm)
    return pm
